name: "Test"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Disallow Concurrent Runs
        uses: ./
        with:
          token: ${{ github.token }}
      - name: Do Busy Work
        run: sleep 30s
